name: dev_2_ì´ë²¤íŠ¸_ì¢…ë¥˜-2025-06-12

on:
  push:
    branches:
      - dev_2_ì´ë²¤íŠ¸_ì¢…ë¥˜-2025-06-12
    paths:
      - '**.md'

jobs:
  dev-02-example-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello and show event info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Post checkout message
        run: |
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo "ğŸ This job's status is ${{ job.status }}."